<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Harmeet-PC" ignored="0" name="Test" tests="6" failures="2" timestamp="2020-11-24T20:07:59 IST" time="0.036" errors="0">
  <testcase name="RetryTC1" time="0.009" classname="com.pcs.retryAnalyzer.NewTest">
    <skipped/>
  </testcase> <!-- RetryTC1 -->
  <testcase name="RetryTC1" time="0.001" classname="com.pcs.retryAnalyzer.NewTest">
    <skipped/>
  </testcase> <!-- RetryTC1 -->
  <testcase name="RetryTC1" time="0.001" classname="com.pcs.retryAnalyzer.NewTest">
    <skipped/>
  </testcase> <!-- RetryTC1 -->
  <testcase name="RetryTC1" time="0.002" classname="com.pcs.retryAnalyzer.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.pcs.retryAnalyzer.NewTest.RetryTC1(NewTest.java:11)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- RetryTC1 -->
  <testcase name="RetryTC2" time="0.001" classname="com.pcs.retryAnalyzer.NewTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.pcs.retryAnalyzer.NewTest.RetryTC2(NewTest.java:16)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- RetryTC2 -->
  <testcase name="RetryTC3" time="0.001" classname="com.pcs.retryAnalyzer.NewTest"/>
</testsuite> <!-- Test -->
